name: Test application
description: Test a NotGovUK application or deployment
inputs:
  app:
    required: false
    type: string
  base-url:
    required: false
    type: string
  browser:
    required: false
    default: 'chromium'
runs:
  using: composite
  steps:

    - name: Install Playwright browser
      shell: bash
      run: npx playwright install --with-deps "${{ inputs.browser }}"

    - name: Run functional tests
      shell: bash
      working-directory: "${{ inputs.app && format('apps/{0}', inputs.app) }}"
      run: "if [[ -z ${PLAYWRIGHT_BASE_URL} ]]; then npm run 'test:functional:ci'; else npm run 'test:functional'; fi;"
      env:
        PLAYWRIGHT_BASE_URL: ${{ inputs.base-url }}
        PLAYWRIGHT_BROWSER: ${{ inputs.browser }}

    - uses: actions/upload-artifact@v6
      if: failure()
      with:
        name: playwright-report-${{ inputs.app }}-${{ inputs.browser }}
        path: playwright-report/
        if-no-files-found: warn

    - uses: actions/upload-artifact@v6
      if: failure()
      with:
        name: playwright-test-results-${{ inputs.app }}-${{ inputs.browser }}
        path: test-results/
        if-no-files-found: warn
