name: Set-up
description: Set-up for building, testing and deployment of NotGovUK projects
inputs:
  node:
    description: The version of Node.js to use.
    required: false
    default: 18
  frozen-lockfile:
    description: Whether to require a frozen lock-file
    required: false
runs:
  using: composite
  steps:

    - name: Set locale
      shell: bash
      run: |
        sudo locale-gen ${{ env.LANG }}
        sudo update-locale LANG=${{ env.LANG }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.33.6
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'

    - name: Cache Cypress.io
      uses: actions/cache@v3
      env:
        cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
      with:
        path: '~/.cache/Cypress'
        key: cypress-os_${{ runner.os }}-lock_${{ env.cache-hash }}

    - name: Pull dependencies
      if: ${{ !inputs.frozen-lockfile || inputs.frozen-lockfile == 'false' }}
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.33.6
        run_install: |
          recursive: true
          args: [--no-frozen-lockfile]

    - name: Pull dependencies (frozen lock-file)
      if: ${{ inputs.frozen-lockfile && inputs.frozen-lockfile != 'false' }}
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.33.6
        run_install: true
