packages:
  - 'apps/**'
  - 'components/**'
  - 'components-internal/**'
  - 'lib/**'
  - 'lib-govuk/**'
  - 'packages/**'
patchedDependencies:
  restify@11.1.0: patches/restify@11.1.0.patch
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  aws-sdk: true
  core-js: true
  core-js-pure: true
  cypress: true
  dtrace-provider: true
  es5-ext: true
  esbuild: true
  fsevents: true
  serverless: true
  sharp: true
  unrs-resolver: true
