name: Publish
description: Publish all public packages
inputs:
  version:
    description: Version to publish
    required: true
  tag:
    description: Npm dist-tag to publish under
    required: false
    default: latest
runs:
  using: composite
  steps:

    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Publish
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        TAG: ${{ inputs.tag }}
      run: |
        npm version "${VERSION}"
        npm run libs:publish -- --tag "${TAG}"
        git push
        git push --tags
