name: Publish
description: Publish all public packages
inputs:
  version:
    description: Version to publish
    required: true
runs:
  using: composite
  steps:

    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Publish
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        npm version "${VERSION}"
        npm run all:publish
        git push
        git push --tags
