name: Update built files
description: Update built files
inputs:
  baseline-branch:
    description: Name of branch to store baseline on
    required: false
    default: master
runs:
  using: composite
  steps:

    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update built files
      shell: bash
      if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', inputs.baseline-branch) }}
      run: |
        git fetch origin $(git rev-parse --abbrev-ref HEAD)
        git merge --ff-only
        cp pnpm-lock.yaml pnpm-lock-committed.yaml
        git add pnpm-lock-committed.yaml
        git commit -m "[skip ci] Update built files" && git push || true
