name: Scan code-base
description: Scans the code-base for credentials and security vulnerabilities
runs:
  using: composite
  steps:

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
