import type { Metadata } from "next";
import React from "react";
//import { Inter } from "next/font/google";
import { Page } from '@hods/components';
/* import "./globals.css"; */

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Page
          navigation={[
            {
              href: "/one",
              text: "One"
            },
            {
              href: "/one/two",
              text: "Two"
            },
            {
              href: "/three",
              text: "Three"
            },
            {
              href: "/four",
              text: "Four"
            }
          ]}
          serviceName="Next.js App"
          serviceHref="/"
          title="HODS"
        >
          {children}
        </Page>
      </body>
    </html>
  );
}
