name: Deploy to Netlify and test
on:
  workflow_call:
    inputs:
      app:
        required: false
        type: string
      node:
        default: 22
        required: false
        type: string
      production-branch:
        default: master
        required: false
        type: string
    secrets:
      CYPRESS_PROJECT_ID:
        required: false
      CYPRESS_RECORD_KEY:
        required: false
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
jobs:
  build-and-deploy:
    name: Build and deploy application
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.deploy.outputs.deploy-url }}
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ inputs.node }}

      - name: Build
        uses: ./.github/actions/build-app
        with:
          app: ${{ inputs.app }}

      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy-to-netlify
        with:
          app: ${{ inputs.app }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          production-branch: ${{ inputs.production-branch }}

  test:
    name: Test
    needs:
      - build-and-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ 'electron' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ inputs.node }}

      - name: Run functional tests
        uses: './.github/actions/test-app'
        with:
          app: ${{ inputs.app }}
          base-url: ${{ needs.build-and-deploy.outputs.deploy-url }}
          browser: ${{ matrix.browser }}
          cypress-project-id: ${{ secrets.CYPRESS_PROJECT_ID }}
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
          deployment: netlify
          node: 22
          smoke: true

      - name: Scan service for vulnerabilities
        uses: './.github/actions/scan-app'
        with:
          app: ${{ inputs.app }}
          baseline-branch: ${{ inputs.production-branch }}
          smoke: true
          target: ${{ needs.build-and-deploy.outputs.deploy-url }}
          token: ${{ secrets.GITHUB_TOKEN }}
