name: Deploy to Heroku and test
on:
  workflow_call:
    inputs:
      app:
        required: false
        type: string
      node:
        required: false
        type: string
        default: 16
    secrets:
      CYPRESS_PROJECT_ID:
        required: false
      CYPRESS_RECORD_KEY:
        required: false
      HEROKU_API_KEY:
        required: true
      HEROKU_APP_NAME:
        required: true
      HEROKU_EMAIL:
        required: true
jobs:
  build-and-deploy:
    name: Build and deploy application
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ inputs.node }}

      - name: Build
        uses: ./.github/actions/build-app
        with:
          app: ${{ inputs.app }}

      - name: Deploy
        uses: ./.github/actions/deploy-to-heroku
        with:
          app: ${{ inputs.app }}
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
          heroku-app-name: ${{ secrets.HEROKU_APP_NAME }}
          heroku-email: ${{ secrets.HEROKU_EMAIL }}

  test:
    name: Test
    needs:
      - build-and-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ 'electron' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ inputs.node }}

      - name: Run functional tests
        uses: './.github/actions/test-app'
        with:
          app: ${{ inputs.app }}
          base-url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
          browser: ${{ matrix.browser }}
          cypress-project-id: ${{ secrets.CYPRESS_PROJECT_ID }}
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
          deployment: heroku
          node: 16
          smoke: true

      - name: Scan service for vulnerabilities
        uses: './.github/actions/scan-app'
        with:
          app: ${{ inputs.app }}
          baseline-branch: ${{ inputs.production-branch }}
          smoke: true
          target: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
          token: ${{ secrets.GITHUB_TOKEN }}
