name: 'Static Security Analysis'
on:
  schedule:
    - cron: '35 1 * * 2'
jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan code-base
        uses: ./.github/actions/scan-code

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: 18

      - name: Scan dependencies
        uses: ./.github/actions/scan-dependencies
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
