name: Update built files
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.sastscan.baseline'
      - 'pnpm-lock.yaml'
jobs:
  common:
    name: Build files
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: 22

      - name: Update built files
        uses: ./.github/actions/update-built-files
        with:
          baseline-branch: 'master'

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan code-base
        uses: ./.github/actions/scan-code
